/- Verse 1.102 — generated from data/contracts/1.102.json. DO NOT EDIT.
   Axiom cites are verbatim commentary quotations, validated by
   tests/test_contracts.py. -/
import VakyaVallari.Adequacy

namespace VakyaVallari.Verses.V1_102

open VakyaVallari

def sphota : Entity := ⟨"sphoṭa", Sorta.manifestation⟩
def karana : Entity := ⟨"karaṇa", Sorta.power⟩
def dhvani : Entity := ⟨"dhvani", Sorta.manifestation⟩
def sabda_ja : Entity := ⟨"śabdajāḥ", Sorta.manifestation⟩
def partless_sphota : Entity := ⟨"partless sphoṭa", Sorta.absolute⟩

def contract : Contract :=
  { axioms := [ Claim.relation "utpadyate" (Node.ent karana) (Node.ent sphota)
    , Claim.relation "sabda_ja" (Node.ent sphota) (Node.ent sabda_ja)
    , Claim.identity sabda_ja dhvani
    , Claim.predication "acoustic" sphota ]
  , denials := [ Claim.identity sphota partless_sphota ] }

def accepted : Reading :=
  { claims := [ Claim.relation "utpadyate" (Node.ent karana) (Node.ent sphota)
    , Claim.relation "sabda_ja" (Node.ent sphota) (Node.ent sabda_ja)
    , Claim.identity sabda_ja dhvani ] }

theorem accepted_adequate : contract.Adequate accepted := by decide

namespace Counterexamples

/- 'The sphota is the partless, metaphysical word-essence that generates secondary acoustic phenomena.'
   Why rejected: Verse 1.102 explicitly reports an alternative view that denies this: the sphota here is acoustic and produced, not partless and metaphysical. This reading confuses Bhartrhari's own doctrine (developed later) with the competing account presented in this verse. -/
def sphota_partless : Reading :=
  { claims := [ Claim.predication "partless" sphota ] }
theorem sphota_partless_inadequate : ¬ contract.Adequate sphota_partless := by decide
#guard contract.licenses sphota_partless = false

/- 'The dhvani are the primary sounds generated by the organs; the sphota is a secondary echo or propagation.'
   Why rejected: Reverses the relation: the verse explicitly states dhvani are sounds *born from* the sphota, making sphota the primary producer. The backward relation is not entailed by the axioms. -/
def dhvani_primary : Reading :=
  { claims := [ Claim.relation "sabda_ja" (Node.ent dhvani) (Node.ent sphota) ] }
theorem dhvani_primary_inadequate : ¬ contract.Adequate dhvani_primary := by decide
#guard contract.licenses dhvani_primary = false

end Counterexamples

end VakyaVallari.Verses.V1_102
