/- Generated verse index. DO NOT EDIT. -/
import VakyaVallari.Verses.V1_1
import VakyaVallari.Verses.V1_10
import VakyaVallari.Verses.V1_11
import VakyaVallari.Verses.V1_12
import VakyaVallari.Verses.V1_13
import VakyaVallari.Verses.V1_14
import VakyaVallari.Verses.V1_15
import VakyaVallari.Verses.V1_16_17
import VakyaVallari.Verses.V1_18_22
import VakyaVallari.Verses.V1_2
import VakyaVallari.Verses.V1_23
import VakyaVallari.Verses.V1_24_26
import VakyaVallari.Verses.V1_27
import VakyaVallari.Verses.V1_28
import VakyaVallari.Verses.V1_29
import VakyaVallari.Verses.V1_3
import VakyaVallari.Verses.V1_30
import VakyaVallari.Verses.V1_31
import VakyaVallari.Verses.V1_32
import VakyaVallari.Verses.V1_33
import VakyaVallari.Verses.V1_34
import VakyaVallari.Verses.V1_35
import VakyaVallari.Verses.V1_36
import VakyaVallari.Verses.V1_37
import VakyaVallari.Verses.V1_38
import VakyaVallari.Verses.V1_39
import VakyaVallari.Verses.V1_4
import VakyaVallari.Verses.V1_40
import VakyaVallari.Verses.V1_41
import VakyaVallari.Verses.V1_42
import VakyaVallari.Verses.V1_43
import VakyaVallari.Verses.V1_44
import VakyaVallari.Verses.V1_45
import VakyaVallari.Verses.V1_46
import VakyaVallari.Verses.V1_47
import VakyaVallari.Verses.V1_48
import VakyaVallari.Verses.V1_49
import VakyaVallari.Verses.V1_5
import VakyaVallari.Verses.V1_50
import VakyaVallari.Verses.V1_51
import VakyaVallari.Verses.V1_52
import VakyaVallari.Verses.V1_53
import VakyaVallari.Verses.V1_54
import VakyaVallari.Verses.V1_55
import VakyaVallari.Verses.V1_56
import VakyaVallari.Verses.V1_57
import VakyaVallari.Verses.V1_58
import VakyaVallari.Verses.V1_59
import VakyaVallari.Verses.V1_6
import VakyaVallari.Verses.V1_60
import VakyaVallari.Verses.V1_61
import VakyaVallari.Verses.V1_62
import VakyaVallari.Verses.V1_63
import VakyaVallari.Verses.V1_64
import VakyaVallari.Verses.V1_65
import VakyaVallari.Verses.V1_66
import VakyaVallari.Verses.V1_67
import VakyaVallari.Verses.V1_68_69
import VakyaVallari.Verses.V1_7
import VakyaVallari.Verses.V1_70
import VakyaVallari.Verses.V1_71
import VakyaVallari.Verses.V1_72
import VakyaVallari.Verses.V1_73
import VakyaVallari.Verses.V1_74
import VakyaVallari.Verses.V1_75
import VakyaVallari.Verses.V1_76
import VakyaVallari.Verses.V1_77
import VakyaVallari.Verses.V1_78
import VakyaVallari.Verses.V1_79
import VakyaVallari.Verses.V1_8
import VakyaVallari.Verses.V1_80
import VakyaVallari.Verses.V1_81
import VakyaVallari.Verses.V1_82
import VakyaVallari.Verses.V1_83
import VakyaVallari.Verses.V1_84
import VakyaVallari.Verses.V1_85
import VakyaVallari.Verses.V1_86
import VakyaVallari.Verses.V1_87
import VakyaVallari.Verses.V1_88
import VakyaVallari.Verses.V1_89
import VakyaVallari.Verses.V1_9
import VakyaVallari.Verses.V1_90
import VakyaVallari.Verses.V1_91
import VakyaVallari.Verses.V1_92
import VakyaVallari.Verses.V1_93
